language: python
python:
  - 3.5
 
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=lxml23

install:
  - pip install -U tox

script:
  - tox

notifications:
  email:
    - gback@mitre.org
    - stix-commits-list@lists.mitre.org
